---
- name: Ensure that the snoopy package is installed
  tags: snoopy
  become: true
  apt:
    name: snoopy
    state: present
  register: snoopy_apt

- name: Applying snoopy configuration
  tags: snoopy
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: snoopy.ini.j2, dst: /etc/snoopy.ini }
    - { src: ld.so.preload.j2, dst: /etc/ld.so.preload }
  when: snoopy_apt|success
...
